// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"database/sql"
	"time"
)

type OidcIdentity struct {
	UserID    string    `json:"user_id"`
	Provider  string    `json:"provider"`
	Subject   string    `json:"subject"`
	CreatedAt time.Time `json:"created_at"`
}

type OidcState struct {
	State        string    `json:"state"`
	Nonce        string    `json:"nonce"`
	CodeVerifier string    `json:"code_verifier"`
	CreatedAt    time.Time `json:"created_at"`
}

type Record struct {
	ID           string         `json:"id"`
	UserID       string         `json:"user_id"`
	Title        string         `json:"title"`
	Artist       string         `json:"artist"`
	Year         sql.NullInt64  `json:"year"`
	Label        sql.NullString `json:"label"`
	Format       sql.NullString `json:"format"`
	Condition    sql.NullString `json:"condition"`
	Genre        sql.NullString `json:"genre"`
	Notes        sql.NullString `json:"notes"`
	CoverArtUrl  sql.NullString `json:"cover_art_url"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
	DiscogsID    sql.NullString `json:"discogs_id"`
	Favorite     int64          `json:"favorite"`
	PersonalNote sql.NullString `json:"personal_note"`
}

type RecordsFt struct {
	Title  string `json:"title"`
	Artist string `json:"artist"`
	Label  string `json:"label"`
	Notes  string `json:"notes"`
}

type RefreshToken struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	TokenHash string `json:"token_hash"`
	ExpiresAt int64  `json:"expires_at"`
	Revoked   int64  `json:"revoked"`
	CreatedAt int64  `json:"created_at"`
}

type User struct {
	ID               string        `json:"id"`
	Email            string        `json:"email"`
	PasswordHash     string        `json:"password_hash"`
	Role             string        `json:"role"`
	FailedLoginCount int64         `json:"failed_login_count"`
	LockedUntil      sql.NullInt64 `json:"locked_until"`
	CreatedAt        int64         `json:"created_at"`
	UpdatedAt        int64         `json:"updated_at"`
	Active           int64         `json:"active"`
}
