// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oidc_states.sql

package sqlcdb

import (
	"context"
	"time"
)

const createOIDCState = `-- name: CreateOIDCState :exec
INSERT INTO oidc_states (state, nonce, code_verifier, created_at)
VALUES (?, ?, ?, ?)
`

type CreateOIDCStateParams struct {
	State        string    `json:"state"`
	Nonce        string    `json:"nonce"`
	CodeVerifier string    `json:"code_verifier"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) CreateOIDCState(ctx context.Context, arg CreateOIDCStateParams) error {
	_, err := q.db.ExecContext(ctx, createOIDCState,
		arg.State,
		arg.Nonce,
		arg.CodeVerifier,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredOIDCStates = `-- name: DeleteExpiredOIDCStates :exec
DELETE FROM oidc_states WHERE created_at < ?
`

func (q *Queries) DeleteExpiredOIDCStates(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredOIDCStates, createdAt)
	return err
}

const deleteOIDCState = `-- name: DeleteOIDCState :exec
DELETE FROM oidc_states WHERE state = ?
`

func (q *Queries) DeleteOIDCState(ctx context.Context, state string) error {
	_, err := q.db.ExecContext(ctx, deleteOIDCState, state)
	return err
}

const findOIDCStateByState = `-- name: FindOIDCStateByState :one
SELECT state, nonce, code_verifier, created_at FROM oidc_states WHERE state = ? LIMIT 1
`

func (q *Queries) FindOIDCStateByState(ctx context.Context, state string) (OidcState, error) {
	row := q.db.QueryRowContext(ctx, findOIDCStateByState, state)
	var i OidcState
	err := row.Scan(
		&i.State,
		&i.Nonce,
		&i.CodeVerifier,
		&i.CreatedAt,
	)
	return i, err
}
