// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oidc_identities.sql

package sqlcdb

import (
	"context"
	"time"
)

const createOIDCIdentity = `-- name: CreateOIDCIdentity :exec
INSERT INTO oidc_identities (user_id, provider, subject, created_at)
VALUES (?, ?, ?, ?)
`

type CreateOIDCIdentityParams struct {
	UserID    string    `json:"user_id"`
	Provider  string    `json:"provider"`
	Subject   string    `json:"subject"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateOIDCIdentity(ctx context.Context, arg CreateOIDCIdentityParams) error {
	_, err := q.db.ExecContext(ctx, createOIDCIdentity,
		arg.UserID,
		arg.Provider,
		arg.Subject,
		arg.CreatedAt,
	)
	return err
}

const findOIDCIdentityByProviderSubject = `-- name: FindOIDCIdentityByProviderSubject :one
SELECT user_id, provider, subject, created_at FROM oidc_identities WHERE provider = ? AND subject = ? LIMIT 1
`

type FindOIDCIdentityByProviderSubjectParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

func (q *Queries) FindOIDCIdentityByProviderSubject(ctx context.Context, arg FindOIDCIdentityByProviderSubjectParams) (OidcIdentity, error) {
	row := q.db.QueryRowContext(ctx, findOIDCIdentityByProviderSubject, arg.Provider, arg.Subject)
	var i OidcIdentity
	err := row.Scan(
		&i.UserID,
		&i.Provider,
		&i.Subject,
		&i.CreatedAt,
	)
	return i, err
}
