// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: records.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const countRecords = `-- name: CountRecords :one
SELECT COUNT(*) FROM records WHERE user_id = ?
`

func (q *Queries) CountRecords(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecords, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRecord = `-- name: CreateRecord :one
INSERT INTO records (id, user_id, title, artist, year, label, format, condition, genre, notes, cover_art_url, discogs_id, favorite, personal_note, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, title, artist, year, label, format, condition, genre, notes, cover_art_url, created_at, updated_at, discogs_id, favorite, personal_note
`

type CreateRecordParams struct {
	ID           string         `json:"id"`
	UserID       string         `json:"user_id"`
	Title        string         `json:"title"`
	Artist       string         `json:"artist"`
	Year         sql.NullInt64  `json:"year"`
	Label        sql.NullString `json:"label"`
	Format       sql.NullString `json:"format"`
	Condition    sql.NullString `json:"condition"`
	Genre        sql.NullString `json:"genre"`
	Notes        sql.NullString `json:"notes"`
	CoverArtUrl  sql.NullString `json:"cover_art_url"`
	DiscogsID    sql.NullString `json:"discogs_id"`
	Favorite     int64          `json:"favorite"`
	PersonalNote sql.NullString `json:"personal_note"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) (Record, error) {
	row := q.db.QueryRowContext(ctx, createRecord,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Artist,
		arg.Year,
		arg.Label,
		arg.Format,
		arg.Condition,
		arg.Genre,
		arg.Notes,
		arg.CoverArtUrl,
		arg.DiscogsID,
		arg.Favorite,
		arg.PersonalNote,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Artist,
		&i.Year,
		&i.Label,
		&i.Format,
		&i.Condition,
		&i.Genre,
		&i.Notes,
		&i.CoverArtUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DiscogsID,
		&i.Favorite,
		&i.PersonalNote,
	)
	return i, err
}

const deleteRecord = `-- name: DeleteRecord :exec
DELETE FROM records WHERE id = ? AND user_id = ?
`

type DeleteRecordParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteRecord(ctx context.Context, arg DeleteRecordParams) error {
	_, err := q.db.ExecContext(ctx, deleteRecord, arg.ID, arg.UserID)
	return err
}

const findDuplicateRecord = `-- name: FindDuplicateRecord :one
SELECT id FROM records
WHERE user_id = ? AND LOWER(title) = LOWER(?) AND LOWER(artist) = LOWER(?)
LIMIT 1
`

type FindDuplicateRecordParams struct {
	UserID  string `json:"user_id"`
	LOWER   string `json:"LOWER"`
	LOWER_2 string `json:"LOWER_2"`
}

func (q *Queries) FindDuplicateRecord(ctx context.Context, arg FindDuplicateRecordParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findDuplicateRecord, arg.UserID, arg.LOWER, arg.LOWER_2)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getRecordByID = `-- name: GetRecordByID :one
SELECT id, user_id, title, artist, year, label, format, condition, genre, notes, cover_art_url, created_at, updated_at, discogs_id, favorite, personal_note FROM records WHERE id = ? AND user_id = ? LIMIT 1
`

type GetRecordByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetRecordByID(ctx context.Context, arg GetRecordByIDParams) (Record, error) {
	row := q.db.QueryRowContext(ctx, getRecordByID, arg.ID, arg.UserID)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Artist,
		&i.Year,
		&i.Label,
		&i.Format,
		&i.Condition,
		&i.Genre,
		&i.Notes,
		&i.CoverArtUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DiscogsID,
		&i.Favorite,
		&i.PersonalNote,
	)
	return i, err
}

const listRecords = `-- name: ListRecords :many
SELECT id, user_id, title, artist, year, label, format, condition, genre, notes, cover_art_url, created_at, updated_at, discogs_id, favorite, personal_note FROM records
WHERE user_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListRecordsParams struct {
	UserID string `json:"user_id"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListRecords(ctx context.Context, arg ListRecordsParams) ([]Record, error) {
	rows, err := q.db.QueryContext(ctx, listRecords, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Record
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Artist,
			&i.Year,
			&i.Label,
			&i.Format,
			&i.Condition,
			&i.Genre,
			&i.Notes,
			&i.CoverArtUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DiscogsID,
			&i.Favorite,
			&i.PersonalNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecord = `-- name: UpdateRecord :one
UPDATE records
SET title = ?,
    artist = ?,
    year = ?,
    label = ?,
    format = ?,
    condition = ?,
    genre = ?,
    notes = ?,
    cover_art_url = ?,
    favorite = ?,
    personal_note = ?,
    updated_at = ?
WHERE id = ? AND user_id = ?
RETURNING id, user_id, title, artist, year, label, format, condition, genre, notes, cover_art_url, created_at, updated_at, discogs_id, favorite, personal_note
`

type UpdateRecordParams struct {
	Title        string         `json:"title"`
	Artist       string         `json:"artist"`
	Year         sql.NullInt64  `json:"year"`
	Label        sql.NullString `json:"label"`
	Format       sql.NullString `json:"format"`
	Condition    sql.NullString `json:"condition"`
	Genre        sql.NullString `json:"genre"`
	Notes        sql.NullString `json:"notes"`
	CoverArtUrl  sql.NullString `json:"cover_art_url"`
	Favorite     int64          `json:"favorite"`
	PersonalNote sql.NullString `json:"personal_note"`
	UpdatedAt    int64          `json:"updated_at"`
	ID           string         `json:"id"`
	UserID       string         `json:"user_id"`
}

func (q *Queries) UpdateRecord(ctx context.Context, arg UpdateRecordParams) (Record, error) {
	row := q.db.QueryRowContext(ctx, updateRecord,
		arg.Title,
		arg.Artist,
		arg.Year,
		arg.Label,
		arg.Format,
		arg.Condition,
		arg.Genre,
		arg.Notes,
		arg.CoverArtUrl,
		arg.Favorite,
		arg.PersonalNote,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Artist,
		&i.Year,
		&i.Label,
		&i.Format,
		&i.Condition,
		&i.Genre,
		&i.Notes,
		&i.CoverArtUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DiscogsID,
		&i.Favorite,
		&i.PersonalNote,
	)
	return i, err
}

const updateRecordCoverArt = `-- name: UpdateRecordCoverArt :exec
UPDATE records SET cover_art_url = ?, updated_at = ? WHERE id = ? AND user_id = ?
`

type UpdateRecordCoverArtParams struct {
	CoverArtUrl sql.NullString `json:"cover_art_url"`
	UpdatedAt   int64          `json:"updated_at"`
	ID          string         `json:"id"`
	UserID      string         `json:"user_id"`
}

func (q *Queries) UpdateRecordCoverArt(ctx context.Context, arg UpdateRecordCoverArtParams) error {
	_, err := q.db.ExecContext(ctx, updateRecordCoverArt,
		arg.CoverArtUrl,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	return err
}
