// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const activateUser = `-- name: ActivateUser :exec
UPDATE users SET active = 1, updated_at = ? WHERE email = ?
`

type ActivateUserParams struct {
	UpdatedAt int64  `json:"updated_at"`
	Email     string `json:"email"`
}

func (q *Queries) ActivateUser(ctx context.Context, arg ActivateUserParams) error {
	_, err := q.db.ExecContext(ctx, activateUser, arg.UpdatedAt, arg.Email)
	return err
}

const changeUserPassword = `-- name: ChangeUserPassword :exec
UPDATE users SET password_hash = ?, updated_at = ? WHERE email = ?
`

type ChangeUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	UpdatedAt    int64  `json:"updated_at"`
	Email        string `json:"email"`
}

func (q *Queries) ChangeUserPassword(ctx context.Context, arg ChangeUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, changeUserPassword, arg.PasswordHash, arg.UpdatedAt, arg.Email)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, password_hash, role, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, email, password_hash, role, failed_login_count, locked_until, created_at, updated_at, active
`

type CreateUserParams struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Active,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users SET active = 0, updated_at = ? WHERE email = ?
`

type DeactivateUserParams struct {
	UpdatedAt int64  `json:"updated_at"`
	Email     string `json:"email"`
}

func (q *Queries) DeactivateUser(ctx context.Context, arg DeactivateUserParams) error {
	_, err := q.db.ExecContext(ctx, deactivateUser, arg.UpdatedAt, arg.Email)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, failed_login_count, locked_until, created_at, updated_at, active FROM users WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Active,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, failed_login_count, locked_until, created_at, updated_at, active FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Active,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, role, failed_login_count, locked_until, created_at, updated_at, active FROM users ORDER BY created_at ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.FailedLoginCount,
			&i.LockedUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetLoginFailure = `-- name: ResetLoginFailure :exec
UPDATE users
SET failed_login_count = 0,
    locked_until = NULL,
    updated_at = ?
WHERE id = ?
`

type ResetLoginFailureParams struct {
	UpdatedAt int64  `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) ResetLoginFailure(ctx context.Context, arg ResetLoginFailureParams) error {
	_, err := q.db.ExecContext(ctx, resetLoginFailure, arg.UpdatedAt, arg.ID)
	return err
}

const updateLoginFailure = `-- name: UpdateLoginFailure :exec
UPDATE users
SET failed_login_count = failed_login_count + 1,
    locked_until = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateLoginFailureParams struct {
	LockedUntil sql.NullInt64 `json:"locked_until"`
	UpdatedAt   int64         `json:"updated_at"`
	ID          string        `json:"id"`
}

func (q *Queries) UpdateLoginFailure(ctx context.Context, arg UpdateLoginFailureParams) error {
	_, err := q.db.ExecContext(ctx, updateLoginFailure, arg.LockedUntil, arg.UpdatedAt, arg.ID)
	return err
}
