// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"zntr.io/vynilino/internal/domain"
)

type AuthPayload struct {
	AccessToken  string       `json:"accessToken"`
	RefreshToken string       `json:"refreshToken"`
	ExpiresIn    int          `json:"expiresIn"`
	User         *domain.User `json:"user"`
}

type CreateRecordInput struct {
	Title       string            `json:"title"`
	Artist      string            `json:"artist"`
	Year        *int              `json:"year,omitempty"`
	Label       *string           `json:"label,omitempty"`
	Format      *domain.Format    `json:"format,omitempty"`
	Condition   *domain.Condition `json:"condition,omitempty"`
	Genres      []string          `json:"genres,omitempty"`
	Notes       *string           `json:"notes,omitempty"`
	CoverArtURL *string           `json:"coverArtUrl,omitempty"`
	DiscogsID   *string           `json:"discogsId,omitempty"`
}

type CreateRecordPayload struct {
	Record           *domain.Record `json:"record"`
	DuplicateWarning *string        `json:"duplicateWarning,omitempty"`
}

type Mutation struct {
}

// Returned by oidcAuthorizationURL — redirect the user to `url`.
type OIDCAuthURLPayload struct {
	// The full authorization URL to redirect the browser to.
	URL string `json:"url"`
	// Opaque state value; pass back to oidcCallback for correlation.
	State string `json:"state"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type RecordChangedEvent struct {
	Type     RecordChangeType `json:"type"`
	Record   *domain.Record   `json:"record,omitempty"`
	RecordID string           `json:"recordId"`
}

type RecordConnection struct {
	Edges      []*RecordEdge `json:"edges"`
	PageInfo   *PageInfo     `json:"pageInfo"`
	TotalCount int           `json:"totalCount"`
}

type RecordEdge struct {
	Cursor string         `json:"cursor"`
	Node   *domain.Record `json:"node"`
}

type RecordFilterInput struct {
	Search        *string           `json:"search,omitempty"`
	Artist        *string           `json:"artist,omitempty"`
	Genre         *string           `json:"genre,omitempty"`
	YearMin       *int              `json:"yearMin,omitempty"`
	YearMax       *int              `json:"yearMax,omitempty"`
	Format        *domain.Format    `json:"format,omitempty"`
	ConditionMin  *domain.Condition `json:"conditionMin,omitempty"`
	FavoritesOnly *bool             `json:"favoritesOnly,omitempty"`
}

type RecordSortInput struct {
	Field     domain.SortField     `json:"field"`
	Direction domain.SortDirection `json:"direction"`
}

type Subscription struct {
}

type UpdateRecordInput struct {
	Title        *string           `json:"title,omitempty"`
	Artist       *string           `json:"artist,omitempty"`
	Year         *int              `json:"year,omitempty"`
	Label        *string           `json:"label,omitempty"`
	Format       *domain.Format    `json:"format,omitempty"`
	Condition    *domain.Condition `json:"condition,omitempty"`
	Genres       []string          `json:"genres,omitempty"`
	Notes        *string           `json:"notes,omitempty"`
	CoverArtURL  *string           `json:"coverArtUrl,omitempty"`
	Favorite     *bool             `json:"favorite,omitempty"`
	PersonalNote *string           `json:"personalNote,omitempty"`
}

type DiscogsSearchType string

const (
	DiscogsSearchTypeRelease DiscogsSearchType = "RELEASE"
	DiscogsSearchTypeMaster  DiscogsSearchType = "MASTER"
	DiscogsSearchTypeAll     DiscogsSearchType = "ALL"
)

var AllDiscogsSearchType = []DiscogsSearchType{
	DiscogsSearchTypeRelease,
	DiscogsSearchTypeMaster,
	DiscogsSearchTypeAll,
}

func (e DiscogsSearchType) IsValid() bool {
	switch e {
	case DiscogsSearchTypeRelease, DiscogsSearchTypeMaster, DiscogsSearchTypeAll:
		return true
	}
	return false
}

func (e DiscogsSearchType) String() string {
	return string(e)
}

func (e *DiscogsSearchType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DiscogsSearchType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DiscogsSearchType", str)
	}
	return nil
}

func (e DiscogsSearchType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DiscogsSearchType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DiscogsSearchType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RecordChangeType string

const (
	RecordChangeTypeCreated RecordChangeType = "CREATED"
	RecordChangeTypeUpdated RecordChangeType = "UPDATED"
	RecordChangeTypeDeleted RecordChangeType = "DELETED"
)

var AllRecordChangeType = []RecordChangeType{
	RecordChangeTypeCreated,
	RecordChangeTypeUpdated,
	RecordChangeTypeDeleted,
}

func (e RecordChangeType) IsValid() bool {
	switch e {
	case RecordChangeTypeCreated, RecordChangeTypeUpdated, RecordChangeTypeDeleted:
		return true
	}
	return false
}

func (e RecordChangeType) String() string {
	return string(e)
}

func (e *RecordChangeType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RecordChangeType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RecordChangeType", str)
	}
	return nil
}

func (e RecordChangeType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RecordChangeType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RecordChangeType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
