package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"
	"fmt"
	"net/http"

	"zntr.io/vynilino/internal/ctxutil"
	"zntr.io/vynilino/internal/domain"
)

// accessCookieName is the HttpOnly cookie that carries the PASETO access token.
const accessCookieName = "vynilino_access"

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

// setAccessCookie writes (or clears) the HttpOnly access-token cookie on the
// current HTTP response (THREAT-006 mitigation).
// Pass ttl > 0 to set the cookie, ttl < 0 to clear it.
func setAccessCookie(ctx context.Context, token string, ttl int) {
	w, ok := ctxutil.ResponseWriterFromContext(ctx)
	if !ok {
		return
	}
	http.SetCookie(w, &http.Cookie{
		Name:     accessCookieName,
		Value:    token,
		Path:     "/",
		MaxAge:   ttl,
		HttpOnly: true,
		Secure:   true,
		SameSite: http.SameSiteStrictMode,
	})
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, email, password string) (*AuthPayload, error) {
	pair, err := r.UserSvc.Register(ctx, email, password)
	if err != nil {
		return nil, gqlErr(err)
	}
	setAccessCookie(ctx, pair.AccessToken, pair.ExpiresIn)
	user, err := r.UserRepo.GetByEmail(ctx, email)
	if err != nil {
		return nil, err
	}
	return authPayload(pair, user), nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email, password string) (*AuthPayload, error) {
	pair, err := r.UserSvc.Login(ctx, email, password)
	if err != nil {
		return nil, gqlErr(err)
	}
	setAccessCookie(ctx, pair.AccessToken, pair.ExpiresIn)
	user, err := r.UserRepo.GetByEmail(ctx, email)
	if err != nil {
		return nil, err
	}
	return authPayload(pair, user), nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, token string) (*AuthPayload, error) {
	pair, err := r.UserSvc.RefreshToken(ctx, token)
	if err != nil {
		return nil, gqlErr(err)
	}
	setAccessCookie(ctx, pair.AccessToken, pair.ExpiresIn)
	userID, err := r.UserSvc.ValidateAccessToken(pair.AccessToken)
	if err != nil {
		return nil, err
	}
	user, err := r.UserRepo.GetByID(ctx, userID)
	if err != nil {
		return nil, err
	}
	return authPayload(pair, user), nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	userID, ok := ctxutil.UserIDFromContext(ctx)
	if !ok {
		return false, errUnauthenticated
	}
	// Clear the access-token cookie (THREAT-006 mitigation).
	setAccessCookie(ctx, "", -1)
	return true, r.UserSvc.Logout(ctx, userID)
}

// OidcAuthorizationURL is the resolver for the oidcAuthorizationURL field.
func (r *mutationResolver) OidcAuthorizationURL(ctx context.Context) (*OIDCAuthURLPayload, error) {
	if r.OIDCSvc == nil {
		return nil, gqlErr(domain.ErrOIDCNotConfigured)
	}
	url, state, err := r.OIDCSvc.AuthorizationURL(ctx)
	if err != nil {
		return nil, gqlErr(err)
	}
	return &OIDCAuthURLPayload{URL: url, State: state}, nil
}

// OidcCallback is the resolver for the oidcCallback field.
func (r *mutationResolver) OidcCallback(ctx context.Context, code, state string) (*AuthPayload, error) {
	if r.OIDCSvc == nil {
		return nil, gqlErr(domain.ErrOIDCNotConfigured)
	}
	pair, err := r.OIDCSvc.HandleCallback(ctx, code, state)
	if err != nil {
		return nil, gqlErr(err)
	}
	setAccessCookie(ctx, pair.AccessToken, pair.ExpiresIn)
	userID, err := r.UserSvc.ValidateAccessToken(pair.AccessToken)
	if err != nil {
		return nil, err
	}
	user, err := r.UserRepo.GetByID(ctx, userID)
	if err != nil {
		return nil, err
	}
	return authPayload(pair, user), nil
}

// CreateRecord is the resolver for the createRecord field.
func (r *mutationResolver) CreateRecord(ctx context.Context, input CreateRecordInput) (*CreateRecordPayload, error) {
	userID, ok := ctxutil.UserIDFromContext(ctx)
	if !ok {
		return nil, errUnauthenticated
	}
	rec := &domain.Record{
		Title:       input.Title,
		Artist:      input.Artist,
		Year:        input.Year,
		Label:       input.Label,
		Format:      input.Format,
		Condition:   input.Condition,
		Genres:      input.Genres,
		Notes:       input.Notes,
		CoverArtURL: input.CoverArtURL,
		DiscogsID:   input.DiscogsID,
	}
	result, err := r.RecordSvc.Create(ctx, userID, rec)
	if err != nil {
		return nil, err
	}
	payload := &CreateRecordPayload{Record: result.Record}
	if result.DuplicateWarning != "" {
		payload.DuplicateWarning = &result.DuplicateWarning
	}
	return payload, nil
}

// UpdateRecord is the resolver for the updateRecord field.
func (r *mutationResolver) UpdateRecord(ctx context.Context, id string, input UpdateRecordInput) (*domain.Record, error) {
	userID, ok := ctxutil.UserIDFromContext(ctx)
	if !ok {
		return nil, errUnauthenticated
	}
	patch := &domain.Record{
		ID:           id,
		Year:         input.Year,
		Label:        input.Label,
		Format:       input.Format,
		Condition:    input.Condition,
		Notes:        input.Notes,
		CoverArtURL:  input.CoverArtURL,
		PersonalNote: input.PersonalNote,
	}
	if input.Title != nil {
		patch.Title = *input.Title
	}
	if input.Artist != nil {
		patch.Artist = *input.Artist
	}
	if input.Genres != nil {
		patch.Genres = input.Genres
	}
	if input.Favorite != nil {
		patch.Favorite = input.Favorite
	}
	return r.RecordSvc.Update(ctx, userID, patch)
}

// DeleteRecord is the resolver for the deleteRecord field.
func (r *mutationResolver) DeleteRecord(ctx context.Context, id string) (bool, error) {
	userID, ok := ctxutil.UserIDFromContext(ctx)
	if !ok {
		return false, errUnauthenticated
	}
	if err := r.RecordSvc.Delete(ctx, id, userID); err != nil {
		if errors.Is(err, domain.ErrNotFound) {
			return false, fmt.Errorf("record not found")
		}
		return false, err
	}
	return true, nil
}

// Record is the resolver for the record field.
func (r *queryResolver) Record(ctx context.Context, id string) (*domain.Record, error) {
	userID, ok := ctxutil.UserIDFromContext(ctx)
	if !ok {
		return nil, errUnauthenticated
	}
	rec, err := r.RecordSvc.GetByID(ctx, id, userID)
	if errors.Is(err, domain.ErrNotFound) {
		return nil, nil
	}
	return rec, err
}

// Records is the resolver for the records field.
func (r *queryResolver) Records(ctx context.Context, first *int, after *string, filter *RecordFilterInput, sort *RecordSortInput) (*RecordConnection, error) {
	userID, ok := ctxutil.UserIDFromContext(ctx)
	if !ok {
		return nil, errUnauthenticated
	}

	limit := 20
	if first != nil && *first > 0 && *first <= 100 {
		limit = *first
	}
	offset := 0
	if after != nil {
		offset = decodeCursor(*after)
	}

	domainFilter := domain.RecordFilter{
		Sort:      domain.SortByCreatedAt,
		Direction: domain.SortDesc,
	}
	if filter != nil {
		domainFilter.Search = filter.Search
		domainFilter.Artist = filter.Artist
		domainFilter.Genre = filter.Genre
		domainFilter.YearMin = filter.YearMin
		domainFilter.YearMax = filter.YearMax
		domainFilter.Format = filter.Format
		domainFilter.ConditionMin = filter.ConditionMin
		if filter.FavoritesOnly != nil {
			domainFilter.FavoritesOnly = *filter.FavoritesOnly
		}
	}
	if sort != nil {
		domainFilter.Sort = domain.SortField(sort.Field)
		domainFilter.Direction = domain.SortDirection(sort.Direction)
	}

	page, err := r.RecordSvc.List(ctx, userID, domainFilter, domain.Page{Limit: limit, Offset: offset})
	if err != nil {
		return nil, err
	}

	edges := make([]*RecordEdge, len(page.Records))
	for i, rec := range page.Records {
		edges[i] = &RecordEdge{Cursor: encodeCursor(offset + i), Node: rec}
	}
	hasNext := offset+len(page.Records) < page.TotalCount
	var startCursor, endCursor *string
	if len(edges) > 0 {
		s, e := edges[0].Cursor, edges[len(edges)-1].Cursor
		startCursor, endCursor = &s, &e
	}
	return &RecordConnection{
		Edges: edges,
		PageInfo: &PageInfo{
			HasNextPage:     hasNext,
			HasPreviousPage: offset > 0,
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
		TotalCount: page.TotalCount,
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*domain.User, error) {
	userID, ok := ctxutil.UserIDFromContext(ctx)
	if !ok {
		return nil, errUnauthenticated
	}
	return r.UserRepo.GetByID(ctx, userID)
}

// SearchDiscogs is the resolver for the searchDiscogs field.
func (r *queryResolver) SearchDiscogs(ctx context.Context, query string, typeArg *DiscogsSearchType) ([]*domain.DiscogsResult, error) {
	if _, ok := ctxutil.UserIDFromContext(ctx); !ok {
		return nil, errUnauthenticated
	}
	searchType := ""
	if typeArg != nil {
		switch *typeArg {
		case DiscogsSearchTypeRelease:
			searchType = "release"
		case DiscogsSearchTypeMaster:
			searchType = "master"
		}
	}
	results, err := r.DiscogsSvc.Search(ctx, query, searchType)
	if err != nil {
		return nil, fmt.Errorf("%s", err.Error())
	}
	out := make([]*domain.DiscogsResult, len(results))
	for i := range results {
		out[i] = &results[i]
	}
	return out, nil
}

// RecordChanged is the resolver for the recordChanged field.
func (r *subscriptionResolver) RecordChanged(ctx context.Context) (<-chan *RecordChangedEvent, error) {
	userID, ok := ctxutil.UserIDFromContext(ctx)
	if !ok {
		return nil, errUnauthenticated
	}

	appCh, unsub := r.RecordSvc.Subscribe(userID)
	gqlCh := make(chan *RecordChangedEvent, 16)

	go func() {
		defer unsub()
		defer close(gqlCh)
		for {
			select {
			case <-ctx.Done():
				return
			case ev, ok := <-appCh:
				if !ok {
					return
				}
				gqlCh <- &RecordChangedEvent{
					Type:     RecordChangeType(ev.Type),
					Record:   ev.Record,
					RecordID: ev.RecordID,
				}
			}
		}
	}()

	return gqlCh, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }
